import os.path as py_path


CURRENT_DIR = py_path.dirname(__file__)
STATIC_DIR = py_path.join(CURRENT_DIR, 'static')
IMAGES_DIR = py_path.join(STATIC_DIR, 'images')

WINDOWS_ICON_PATH = py_path.join(IMAGES_DIR, 'icon.ico')

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_TITLE = 'CarSim ETTI - ScorpionIPX'

MIN_FPS = 24
MAX_FPS = 36


FL_VEL_LABEL_X = 250
FL_VEL_LABEL_Y = 380
FR_VEL_LABEL_X = 250
FR_VEL_LABEL_Y = 525
RL_VEL_LABEL_X = 535
RL_VEL_LABEL_Y = 370
RR_VEL_LABEL_X = 535
RR_VEL_LABEL_Y = 505

FL_PRES_LABEL_X = 180
FL_PRES_LABEL_Y = 280
FR_PRES_LABEL_X = 180
FR_PRES_LABEL_Y = 425
RL_PRES_LABEL_X = 670
RL_PRES_LABEL_Y = 280
RR_PRES_LABEL_X = 670
RR_PRES_LABEL_Y = 425

FL_PRES_PBAR_X = 150
FL_PRES_PBAR_Y = 280
FR_PRES_PBAR_X = 150
FR_PRES_PBAR_Y = 425
RL_PRES_PBAR_X = 640
RL_PRES_PBAR_Y = 280
RR_PRES_PBAR_X = 640
RR_PRES_PBAR_Y = 425

PRES_PBAR_MIN = 0
PRES_PBAR_MAX = 250
