import os.path as py_path


CURRENT_DIR = py_path.dirname(__file__)
STATIC_DIR = py_path.join(CURRENT_DIR, 'static')
IMAGES_DIR = py_path.join(STATIC_DIR, 'images')

WINDOWS_ICON_PATH = py_path.join(IMAGES_DIR, 'icon.ico')

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_TITLE = 'CarSim ETTI - ScorpionIPX'

FPS = 25


FL_VEL_LABEL_X = 100
FL_VEL_LABEL_Y = 100
FR_VEL_LABEL_X = 100
FR_VEL_LABEL_Y = 150
RL_VEL_LABEL_X = 150
RL_VEL_LABEL_Y = 100
RR_VEL_LABEL_X = 150
RR_VEL_LABEL_Y = 150

FL_PRES_LABEL_X = 400
FL_PRES_LABEL_Y = 400
FR_PRES_LABEL_X = 400
FR_PRES_LABEL_Y = 450
RL_PRES_LABEL_X = 450
RL_PRES_LABEL_Y = 400
RR_PRES_LABEL_X = 450
RR_PRES_LABEL_Y = 450

FL_PRES_PBAR_X = 300
FL_PRES_PBAR_Y = 300
FR_PRES_PBAR_X = 300
FR_PRES_PBAR_Y = 350
RL_PRES_PBAR_X = 350
RL_PRES_PBAR_Y = 300
RR_PRES_PBAR_X = 350
RR_PRES_PBAR_Y = 350

PRES_PBAR_MIN = 0
PRES_PBAR_MAX = 250
